fw = open('notice.txt', 'w')
fw.write('Hi everyone!\n')
fw.write('Here is the instruction for you to follow:\n')
fw.write('Save Electricity\n')
fw.write('Save water\n')
fw.close()

fr = open('notice.txt', 'r')
text = fr.read()
print(text)
fr.close()